FROM nginx:stable-alpine

LABEL maintainer="HoaDX <duongxuanhoa@gmail.com>"

ENV NGINX_VERSION=1.13.6
ENV USERNAME=nginx
ENV GROUPNAME=nginx
ENV USER_ID=101
ENV GROUP_ID=101
ENV CHANGE_OWNER=0

COPY docker-entrypoint.sh /

